/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx"
import { Route as SignupRouteImport } from "./routes/signup.tsx"
import { Route as IndexRouteImport } from "./routes/index.tsx"
import { Route as SettingsIndexRouteImport } from "./routes/settings.index.tsx"
import { Route as SettingsCommunicationRouteImport } from "./routes/settings.communication.tsx"
import { Route as SettingsAdminRouteImport } from "./routes/settings.admin.tsx"
import { Route as SettingsFeedbackIndexRouteImport } from "./routes/settings.feedback.index.tsx"
import { Route as SettingsAdminUsersRouteImport } from "./routes/settings.admin.users.tsx"
import { Route as ApiAuthSplatRouteImport } from "./routes/api.auth.$.ts"

const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCommunicationRoute = SettingsCommunicationRouteImport.update({
  id: "/settings/communication",
  path: "/settings/communication",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAdminRoute = SettingsAdminRouteImport.update({
  id: "/settings/admin",
  path: "/settings/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFeedbackIndexRoute = SettingsFeedbackIndexRouteImport.update({
  id: "/settings/feedback/",
  path: "/settings/feedback/",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAdminUsersRoute = SettingsAdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => SettingsAdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/signup": typeof SignupRoute
  "/settings/admin": typeof SettingsAdminRouteWithChildren
  "/settings/communication": typeof SettingsCommunicationRoute
  "/settings": typeof SettingsIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/settings/admin/users": typeof SettingsAdminUsersRoute
  "/settings/feedback": typeof SettingsFeedbackIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/signup": typeof SignupRoute
  "/settings/admin": typeof SettingsAdminRouteWithChildren
  "/settings/communication": typeof SettingsCommunicationRoute
  "/settings": typeof SettingsIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/settings/admin/users": typeof SettingsAdminUsersRoute
  "/settings/feedback": typeof SettingsFeedbackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/signup": typeof SignupRoute
  "/settings/admin": typeof SettingsAdminRouteWithChildren
  "/settings/communication": typeof SettingsCommunicationRoute
  "/settings/": typeof SettingsIndexRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
  "/settings/admin/users": typeof SettingsAdminUsersRoute
  "/settings/feedback/": typeof SettingsFeedbackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/signup"
    | "/settings/admin"
    | "/settings/communication"
    | "/settings"
    | "/api/auth/$"
    | "/settings/admin/users"
    | "/settings/feedback"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/signup"
    | "/settings/admin"
    | "/settings/communication"
    | "/settings"
    | "/api/auth/$"
    | "/settings/admin/users"
    | "/settings/feedback"
  id:
    | "__root__"
    | "/"
    | "/signup"
    | "/settings/admin"
    | "/settings/communication"
    | "/settings/"
    | "/api/auth/$"
    | "/settings/admin/users"
    | "/settings/feedback/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignupRoute: typeof SignupRoute
  SettingsAdminRoute: typeof SettingsAdminRouteWithChildren
  SettingsCommunicationRoute: typeof SettingsCommunicationRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SettingsFeedbackIndexRoute: typeof SettingsFeedbackIndexRoute
}

declare module "@tanstack/solid-router" {
  interface FileRoutesByPath {
    "/signup": {
      id: "/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/": {
      id: "/settings/"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/communication": {
      id: "/settings/communication"
      path: "/settings/communication"
      fullPath: "/settings/communication"
      preLoaderRoute: typeof SettingsCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/admin": {
      id: "/settings/admin"
      path: "/settings/admin"
      fullPath: "/settings/admin"
      preLoaderRoute: typeof SettingsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/feedback/": {
      id: "/settings/feedback/"
      path: "/settings/feedback"
      fullPath: "/settings/feedback"
      preLoaderRoute: typeof SettingsFeedbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings/admin/users": {
      id: "/settings/admin/users"
      path: "/users"
      fullPath: "/settings/admin/users"
      preLoaderRoute: typeof SettingsAdminUsersRouteImport
      parentRoute: typeof SettingsAdminRoute
    }
    "/api/auth/$": {
      id: "/api/auth/$"
      path: "/api/auth/$"
      fullPath: "/api/auth/$"
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsAdminRouteChildren {
  SettingsAdminUsersRoute: typeof SettingsAdminUsersRoute
}

const SettingsAdminRouteChildren: SettingsAdminRouteChildren = {
  SettingsAdminUsersRoute: SettingsAdminUsersRoute,
}

const SettingsAdminRouteWithChildren = SettingsAdminRoute._addFileChildren(
  SettingsAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignupRoute: SignupRoute,
  SettingsAdminRoute: SettingsAdminRouteWithChildren,
  SettingsCommunicationRoute: SettingsCommunicationRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SettingsFeedbackIndexRoute: SettingsFeedbackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.ts"
import type { createStart } from "@tanstack/solid-start"
declare module "@tanstack/solid-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
